# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c30ea6faec745592fb4eaeebb988bca3a765af2561eba4106ddb057df09402cf554baf72ead99380382f2d1eb7bb8c791db6256a1fcc768a30954e427e2e742

test:
  secret_key_base: 7e9ff9592d7882be805db1bbaf6d5f8a945e49c4992ff2b0ec7bd9dc497ef90afca8e751dd5885423f38fa09c2ccb0cd3af94b11ba880c3ddbcf13955a1a19ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
